{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.module",
    "module": "aptprocessor",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aptprocessor-1.0.jar",
          "url": "aptprocessor-1.0.jar",
          "size": 11463,
          "sha512": "d77f7b1a5ef65e7c51618b0ddc3d2447963ed5e42d5508a4cc11e910b1569fdb0d88f42bf093cd877f6c3725718eb37382288b1703c7f87c2b6faf2681003260",
          "sha256": "a68beb4af0a287e159354c0e4d93604676e415028e84f7361b71568f2ad27be2",
          "sha1": "eb2abc5fe8a15d3079a64198ac16f864fa075b66",
          "md5": "96d6ad76052d6a76e5bc25fbc8f38719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.ray.module",
          "module": "aptannotation",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.ray.module",
          "module": "network",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-ksp",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "aptprocessor-1.0.jar",
          "url": "aptprocessor-1.0.jar",
          "size": 11463,
          "sha512": "d77f7b1a5ef65e7c51618b0ddc3d2447963ed5e42d5508a4cc11e910b1569fdb0d88f42bf093cd877f6c3725718eb37382288b1703c7f87c2b6faf2681003260",
          "sha256": "a68beb4af0a287e159354c0e4d93604676e415028e84f7361b71568f2ad27be2",
          "sha1": "eb2abc5fe8a15d3079a64198ac16f864fa075b66",
          "md5": "96d6ad76052d6a76e5bc25fbc8f38719"
        }
      ]
    }
  ]
}
