{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.utils",
    "module": "update",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.AgpVersionAttr": "7.3.0",
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "update-1.0.0-SNAPSHOT.aar",
          "url": "update-1.0.0-SNAPSHOT.aar",
          "size": 22224,
          "sha512": "b9466421badc5eac7efee3f78f3c202a73b4697bbf8d82a2666419ee05f35ce6b580726c0da6b555038db978ae8fd6e078676ea6bf1879dda850866337341509",
          "sha256": "ae23f1908779e5bbb07869532c80136ad9a933df74d3f9cafe92f23b722badf6",
          "sha1": "a024d2ad91a1f76103d388ee2e5bb5ccce51e91e",
          "md5": "c087fddf43a42908b98318ab70a0d4c3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.AgpVersionAttr": "7.3.0",
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "update-1.0.0-SNAPSHOT.aar",
          "url": "update-1.0.0-SNAPSHOT.aar",
          "size": 22224,
          "sha512": "b9466421badc5eac7efee3f78f3c202a73b4697bbf8d82a2666419ee05f35ce6b580726c0da6b555038db978ae8fd6e078676ea6bf1879dda850866337341509",
          "sha256": "ae23f1908779e5bbb07869532c80136ad9a933df74d3f9cafe92f23b722badf6",
          "sha1": "a024d2ad91a1f76103d388ee2e5bb5ccce51e91e",
          "md5": "c087fddf43a42908b98318ab70a0d4c3"
        }
      ]
    }
  ]
}
