{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.module",
    "module": "network",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "network-1.0.jar",
          "url": "network-1.0.jar",
          "size": 29477,
          "sha512": "3802b53b659c71e2aa73457de44caefb535601bbade918aacffab5e9e02a348676a47a9819135805d71e9b7a4b3f42b29fa603343b3fe8dd330d83c890917105",
          "sha256": "68cf8d0e1422738c5a85c331b87cfd86324cd9423cce75b6aeae4507a2291a01",
          "sha1": "8e68c3377ffc42cbe59e964e18ff28049c947359",
          "md5": "704c4ebf1adaa772b8509713ebe115e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.8.1"
          },
          "excludes": [
            {
              "group": "com.google.code.gson",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "net.sf.json-lib",
          "module": "json-lib",
          "version": {
            "requires": "2.4"
          },
          "excludes": [
            {
              "group": "commons-beanutils",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "json-lib",
              "type": "jar",
              "extension": "jar",
              "classifier": "jdk15"
            }
          }
        }
      ],
      "files": [
        {
          "name": "network-1.0.jar",
          "url": "network-1.0.jar",
          "size": 29477,
          "sha512": "3802b53b659c71e2aa73457de44caefb535601bbade918aacffab5e9e02a348676a47a9819135805d71e9b7a4b3f42b29fa603343b3fe8dd330d83c890917105",
          "sha256": "68cf8d0e1422738c5a85c331b87cfd86324cd9423cce75b6aeae4507a2291a01",
          "sha1": "8e68c3377ffc42cbe59e964e18ff28049c947359",
          "md5": "704c4ebf1adaa772b8509713ebe115e0"
        }
      ]
    }
  ]
}
