{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.settings",
    "module": "easysettings",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "easysettings-1.0.0.jar",
          "url": "easysettings-1.0.0.jar",
          "size": 65409,
          "sha512": "ef33a85f77fbc090f48db1cb75293786428858592782870fa2ff75147a2dfdcb7617bbb38a88dc1a012cb12da5b8c254e4f299e73108f8540234d15bdb1966cb",
          "sha256": "d513c2a0d983949045442bcb6ff21589d77d526aba7a77f04c0952ac2f9f61c8",
          "sha1": "17ed000506a8e1fe86fd4bff3749fed928cf9f26",
          "md5": "3f873205f6d629eed830bf2009d0b7c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "easysettings-1.0.0.jar",
          "url": "easysettings-1.0.0.jar",
          "size": 65409,
          "sha512": "ef33a85f77fbc090f48db1cb75293786428858592782870fa2ff75147a2dfdcb7617bbb38a88dc1a012cb12da5b8c254e4f299e73108f8540234d15bdb1966cb",
          "sha256": "d513c2a0d983949045442bcb6ff21589d77d526aba7a77f04c0952ac2f9f61c8",
          "sha1": "17ed000506a8e1fe86fd4bff3749fed928cf9f26",
          "md5": "3f873205f6d629eed830bf2009d0b7c0"
        }
      ]
    }
  ]
}
