{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.settings",
    "module": "easysettings",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "easysettings-1.0.0.jar",
          "url": "easysettings-1.0.0.jar",
          "size": 63147,
          "sha512": "cd74b4dd98f510ce2e89dec7e0a3536e7dec169d7cbe0509708f441bc4532ee24813cd2d040524bc92885a7eb40006fd7fef3c2f68e13c6125043d3194003d39",
          "sha256": "26edf70381a6b1c8a462f85884981edcc75480286ac9cd1f8d7d62b661cba5d0",
          "sha1": "d5417b0ac0b3ecc68c66478f19df9729bd82d9cc",
          "md5": "8917cce5334738008addfa7ab4ab250f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "easysettings-1.0.0.jar",
          "url": "easysettings-1.0.0.jar",
          "size": 63147,
          "sha512": "cd74b4dd98f510ce2e89dec7e0a3536e7dec169d7cbe0509708f441bc4532ee24813cd2d040524bc92885a7eb40006fd7fef3c2f68e13c6125043d3194003d39",
          "sha256": "26edf70381a6b1c8a462f85884981edcc75480286ac9cd1f8d7d62b661cba5d0",
          "sha1": "d5417b0ac0b3ecc68c66478f19df9729bd82d9cc",
          "md5": "8917cce5334738008addfa7ab4ab250f"
        }
      ]
    }
  ]
}
