{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.settings",
    "module": "easysettings",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "easysettings-1.0.0.jar",
          "url": "easysettings-1.0.0.jar",
          "size": 63168,
          "sha512": "9429e8826ac3efa895150efe8439fab011f29a5c001ddf1d3be885a09f8a07ea7a21b93e23cf7607c40f961be0045f2ff36b108cd353f78642dd0556399e51f9",
          "sha256": "3042fca84b19cfa0b21fa536000b04865e529c7a0fab1733b6d33c07f4600c0f",
          "sha1": "b6ef13410f7ccb7d51c024c13c350b1f67de3bc7",
          "md5": "df013614009145f2bb4e27b0d3cab9ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "easysettings-1.0.0.jar",
          "url": "easysettings-1.0.0.jar",
          "size": 63168,
          "sha512": "9429e8826ac3efa895150efe8439fab011f29a5c001ddf1d3be885a09f8a07ea7a21b93e23cf7607c40f961be0045f2ff36b108cd353f78642dd0556399e51f9",
          "sha256": "3042fca84b19cfa0b21fa536000b04865e529c7a0fab1733b6d33c07f4600c0f",
          "sha1": "b6ef13410f7ccb7d51c024c13c350b1f67de3bc7",
          "md5": "df013614009145f2bb4e27b0d3cab9ab"
        }
      ]
    }
  ]
}
