{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.settings",
    "module": "easysettings",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "easysettings-2.0.0.jar",
          "url": "easysettings-2.0.0.jar",
          "size": 73544,
          "sha512": "74bc5b2c76fef5c5e2888bbd541ef0b1509042c2ff7ddc0869cb824ea4a56362999e1320ff628c659628256da068376534d7db30e7c14cff8335f4c1985069e6",
          "sha256": "081f792626d11f0e9e5b2d907ebf48dba5edba8f4a97f671e0970ee6c908a0b0",
          "sha1": "b835fa7a15ca4671323d684157e9e2a8ed73eb60",
          "md5": "047c69bbc0c09646f77dd19ae42e2e24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "easysettings-2.0.0.jar",
          "url": "easysettings-2.0.0.jar",
          "size": 73544,
          "sha512": "74bc5b2c76fef5c5e2888bbd541ef0b1509042c2ff7ddc0869cb824ea4a56362999e1320ff628c659628256da068376534d7db30e7c14cff8335f4c1985069e6",
          "sha256": "081f792626d11f0e9e5b2d907ebf48dba5edba8f4a97f671e0970ee6c908a0b0",
          "sha1": "b835fa7a15ca4671323d684157e9e2a8ed73eb60",
          "md5": "047c69bbc0c09646f77dd19ae42e2e24"
        }
      ]
    }
  ]
}
