{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.settings",
    "module": "easysettings",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "easysettings-2.0.0.jar",
          "url": "easysettings-2.0.0.jar",
          "size": 73616,
          "sha512": "cd8532500d1a4c0629f51c460eac648e9c17b7e3911727139dff4eac1cf9d125cbefad64a786a5b6ae46e82b07de9ea7b6c3a8c3adf12d33cb339d473f143c1a",
          "sha256": "69c863959289185b2022e631257f7fa455d0cc62bb0f538ab0c8504515771754",
          "sha1": "c98f883431df08cbfd7039a3b98bc00aa2f1a7ce",
          "md5": "90d90ea872da823bdfef05f56789a2ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "easysettings-2.0.0.jar",
          "url": "easysettings-2.0.0.jar",
          "size": 73616,
          "sha512": "cd8532500d1a4c0629f51c460eac648e9c17b7e3911727139dff4eac1cf9d125cbefad64a786a5b6ae46e82b07de9ea7b6c3a8c3adf12d33cb339d473f143c1a",
          "sha256": "69c863959289185b2022e631257f7fa455d0cc62bb0f538ab0c8504515771754",
          "sha1": "c98f883431df08cbfd7039a3b98bc00aa2f1a7ce",
          "md5": "90d90ea872da823bdfef05f56789a2ec"
        }
      ]
    }
  ]
}
