{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ray.settings",
    "module": "easysettings",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "easysettings-2.0.0.jar",
          "url": "easysettings-2.0.0.jar",
          "size": 73589,
          "sha512": "f592fdea1ce85f423b633a1ee7e3fc58ffbca4061413db3bb35b8ac0a5747fd3ea1ddb3c3f81409cc38c32a7f187efb05034813092081f6decb82aa08593a093",
          "sha256": "f5a4a2f97c950b96ddf39d29423bb39d5970e4f0d3adb4c8bc810fb62ab41258",
          "sha1": "07b7be3321b505ff8188637dc486fc8995b75d07",
          "md5": "20fb803987a86b98b642a49735b79dac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "easysettings-2.0.0.jar",
          "url": "easysettings-2.0.0.jar",
          "size": 73589,
          "sha512": "f592fdea1ce85f423b633a1ee7e3fc58ffbca4061413db3bb35b8ac0a5747fd3ea1ddb3c3f81409cc38c32a7f187efb05034813092081f6decb82aa08593a093",
          "sha256": "f5a4a2f97c950b96ddf39d29423bb39d5970e4f0d3adb4c8bc810fb62ab41258",
          "sha1": "07b7be3321b505ff8188637dc486fc8995b75d07",
          "md5": "20fb803987a86b98b642a49735b79dac"
        }
      ]
    }
  ]
}
